#!/usr/bin/env bash

REGION_LIST="us-east-1 us-east-2 us-west-1 us-west-2 ap-south-1 ap-northeast-2  ap-southeast-1  ap-southeast-2  ap-northeast-1  ca-central-1  eu-central-1  eu-west-1  eu-west-2 eu-west-3  eu-north-1 sa-east-1"

for REGION in ${REGION_LIST}
do
  echo '
provider aws {
  alias = "REGION"
  region = "REGION"
} ' | sed -e "s/REGION/${REGION}/g"

done

#module REGION {
#  source       = "./modules/region"
#  providers = {
#    aws = aws.REGION
#  }
#  enable       = contains(local.enalbed_regions, "REGION")
#  account_info = local.account_info
#} ' | sed -e "s/REGION/${REGION}/g"